create table Routes(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       description TEXT,
                       price REAL  CHECK (price >=0),
                       grade REAL CHECK ( grade >=0 AND price <=10)
)